### ISSUE TITLE
Section 3.6.2 and 3.6.3 are on the same topic (sdcMicro) - almost same content !!

### ISSUE THREAD

**Issue by julienjamme** [julienjamme/handbook_sdc_from_doc_to_md#119]
Which of these do we have to remove ? 
I would say that 3.6.2 is the good one, but not sure.

**Comment by ppdewolf** [comment]
I think 3.6.3 is the correct one. Based on the fact that

1.       3.6.3 a a little bit more content at the end (also about the graphical user interface of sdcMicro)

2.       At the end of 3.6.2 the architecture of mu-argus is mentioned

So I would vote to keep 3.6.3 and remove 3.6.2


Van: Julien Jamme ***@***.***>
Verzonden: vrijdag 2 augustus 2024 21:18
Aan: julienjamme/handbook_sdc_from_doc_to_md ***@***.***>
CC: Peter-Paul de Wolf ***@***.***>; Assign ***@***.***>
Onderwerp: [*Nieuwsbrief*] [julienjamme/handbook_sdc_from_doc_to_md] Section 3.6.2 and 3.6.3 are on the same topic (sdcMicro) - almost same content !! (Issue #119)

[Externe email]

Which of these do we have to remove ?
I would say that 3.6.2 is the good one, but not sure.

**Comment by ppdewolf** [comment]
Taken care of in #125

**Comment by julienjamme** [comment]
Thanks @ppdewolf !
