### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ppdewolf** [julienjamme/handbook_sdc_from_doc_to_md#134]
Just a question: the titlepage for the pdf-version is a separate LaTeX document? So not included in any of the qmd files?
If so, I might have an look at adjustign the linespace between the two lines of the title.

**Comment by julienjamme** [comment]
Yes the two first pages of the pdf are handled by the _titlepage.tex file.

If you need some specific latex package, you have to add it in the include-header section of the _quarto.yml file.

**Comment by ppdewolf** [comment]
Just made a pull request for a small hack to take care of the linespacing in the title
