### ISSUE TITLE
Where to place the "final" version

### ISSUE THREAD

**Issue by ppdewolf** [julienjamme/handbook_sdc_from_doc_to_md#150]
We still need to decide where to put the sources and where to have the online version located.

- We can put the sources in sdcTools environment? How do we do that? Fork it to sdcTools?
- Perhaps we can have the online version as part of https://sdctools.github.io? How? Including automatic build of pdf?

**Comment by julienjamme** [comment]
A fork would mean that my repo remains the reference, it wouldn't be relevant for the future.

In my opinion, the best option is to create e new repo on sdctools and move only the material needed from my repo to the new one. On this repo, we can create new gh-pages to ensure a CI/CD that deploys the pdf and the html versions.
All the stuff needed to do this is already in the repo. 

I let you create the repo and after that I can try to move the repo (not all the stuff only necessary stuff: for example all the code to translate the .doc file to a quarto book is not useful for the final repo) and create the CI/CD. 

What do you think ?

**Comment by ppdewolf** [comment]
Okay. 
I've created a repo (HandbookSDC) and a team (Contributors/authors HandbookSDC). The team for now has write access.
I've given you admin rights, so you can set up the repo the way you want, including rules for the main branch, adding/replacing people in the team, etc.

I guess the online version will then be added to https://sdctools.github.io/HandbookSDC or something like that?

**Comment by julienjamme** [comment]
Yes the URL should be like that.
I'll move the repo by the end of the week. I let you when it's done.

**Comment by ppdewolf** [comment]
Okay. So we can already add the place for the online version to the Preface of the pdf-version that I will send to Eurostat on Monday 26 August? Will you do that?

See 
```
::: {.content-visible when-format="pdf"}

::: {.callout-tip appearance="simple"}
An online version of this handbook can be found at [To be decided](ToBeDecided)
:::

:::
```
in the `index.qmd`

**Comment by julienjamme** [comment]
Yes I'll modify the index.qmd file as soon as I know the definitive link.

**Comment by julienjamme** [comment]
The moving to HandbookSDC repo is done and complete for me.
I've also found a way to make the download link of the pdf version direct.
The modification from the last pull request has not been taken into account because it was not merged when I did the move. But it won't be difficult to do this directly on the final repo. 

Let me know if you see something going wrong !

**Comment by ppdewolf** [comment]
Looks good so far. Thanks!. I'll close the issue now.
For the pull request: I'll make a new one removing the same reference.
