### ISSUE TITLE
at the very end of ch. 3.4.4.1., there is an eq. missing:

### ISSUE THREAD

**Issue by violetacln** [julienjamme/handbook_sdc_from_doc_to_md#16]
\rho (z_j, z_l)=\frac{Cov(Z_j, Z_l}{\sqrt{V(X_j)V(X_l)}} = \frac{1}{1+\alpha} \rho(x_j, x_l),\forall j \neq l

Caution: 
the original seems to me wrongly typed and I did here a correction already! (see brackets around z_j, z_l and around x_j, x_l

**Comment by julienjamme** [comment]
I follow you on this !
