### ISSUE TITLE
Harmonization of styles and formats (outside of math mode)

### ISSUE THREAD

**Issue by mamoeh** [julienjamme/handbook_sdc_from_doc_to_md#60]
Some aspects on which a coherent line (throughout all chapters) might benefit readability:

- Capitalizing (or not) of attribute names ('Geography' vs. 'geography', 'Size Class' vs. 'size class' vs. 'Size class')
- The same for technical terms ('Controlled Rounding' vs. 'controlled rounding' vs. 'Controlled rounding')
- When introducing or emphasizing a term: single ticks, double ticks, or italics ('marginal cells' vs. "marginal cells" vs. *marginal cells*)

Maybe complete harmonization is not feasible, but I think at least the writing of technical terms should be coherent.

**Comment by julienjamme** [comment]
Totally agree to try a complete harmonization. Maybe you could suggest a minimal list of terms to harmonize and a way to write them.
