### ISSUE TITLE
example references in the word document

### ISSUE THREAD

**Issue by simonkolb** [julienjamme/handbook_sdc_from_doc_to_md#61]
Hi, when looking through 4.2.1 I noticed that the word documents makes references to these subsection which are located on the left of the text. Its mostly about references to examples in this section. If you search ctrl+f for "example 1" starting on page 118 you will find multiple instances of these references in the text. 

section and line number in repo:
4.2.1 
line 57  ref:1b 
https://github.com/r-tent/handbook_sdc_from_doc_to_md_destatis/blob/8a33819b5a93dbd46f8b157121297c2ad924f255/chapters/04/_04-magnitude-tabular-data-02-Disclosure-Control-Concepts-for-Magnitude-Tabular-Data.qmd#LL57C2-L57C2

line 61,63  ref:1c
https://github.com/r-tent/handbook_sdc_from_doc_to_md_destatis/blob/8a33819b5a93dbd46f8b157121297c2ad924f255/chapters/04/_04-magnitude-tabular-data-02-Disclosure-Control-Concepts-for-Magnitude-Tabular-Data.qmd#L61

line 27   ref:1d
 https://github.com/r-tent/handbook_sdc_from_doc_to_md_destatis/blob/8a33819b5a93dbd46f8b157121297c2ad924f255/chapters/04/_04-magnitude-tabular-data-02-Disclosure-Control-Concepts-for-Magnitude-Tabular-Data.qmd#L27

These are only some findings for 4.2.1.

**Comment by julienjamme** [comment]
Thank you for your remark. Indeed, the left subtitles of the manual have disappeared. I suggest to add it manually as a 4th level header. 
# Magnitude tabular data (1st level)
## Disclosure Control Concepts ... (2nd)
### Sensitive cells in Magnitude tables (3rd)
#### Example 1b

What do you think about it ?

**Comment by simonkolb** [comment]
I have little experience working on these things, but your suggestion seems reasonable. Could you provide an example code snippet in order to introduce these additional headers?

**Comment by julienjamme** [comment]
To add a title or subtitle, it's very simple: you just have use `#`s at the beginning of a line, as follows:

`# Magnitude tabular data` refers to a 1st level title
`## Disclosure Control Concepts` refers to a 2nd level title

Then, for a 4th level title, before the title you write 4 `#` at the beginning of the line:
For example, `#### Example 1b` to produce a 4th level title.

Hope this is understandable.
