### ISSUE TITLE
Where to place TRS

### ISSUE THREAD

**Issue by ppdewolf** [julienjamme/handbook_sdc_from_doc_to_md#74]
In the description of TRS (currently in chapter on microdata protection) it is stated that
<blockquote>
Although it is applied solely on micro data it is generally considered a protection method used for tabular data and not recommended for protecting micro data.
</blockquote>

Should we better mention this as a pre-tabular method in the table protection chapters? Or should we keep it as it is (in Chapter 3)?

**Comment by JohannesGuss** [comment]
@ppdewolf sorry for the very delayed reaction. I am open to move this chapter, if that suits the handbook better.

**Comment by ppdewolf** [comment]
Adjusted
